server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: rws
          uri: http://localhost:8100/
          predicates:
            - Path=/rws/**
          filters:
            - RewritePath=/rws(?<segment>/?.*), /api/v1/$\{segment}
            #- SetPath=/api/v1/**
            #- StripPrefix=1
            #- AddRequestHeader=X-IBM-Client-Id, devKey
            #- AddRequestHeader=X-IBM-Client-Secret, Secret
        - id: astro
          uri: http://localhost:8200/
          predicates:
            - Path=/astro/**
          filters:
            - RewritePath=/astro(?<segment>/?.*), /api/v1$\{segment}
